### ISSUE TITLE
Micro Vehicles not appearing in Entities tab.

### ISSUE THREAD

**Issue by Lumit1c** [Xerasin/XMV#1]
Im playing Gmod, and I got your (very good by the looks of the pics) mod. I couldn't find the micro vehicles, so I checked the description, it says it's in Entities, I look in all tabs of the Entities category, and I can't find it, am I doing something wrong or is this a bug?

**Comment by Xerasin** [comment]
Closed due to age, comment if this is still an issue for you and I'll reopen.
